### ISSUE TITLE
Design presentation template

### ISSUE THREAD

**Issue by cassiemc** [mozillascience/working-open-workshop#12]
Styles for this can be based on the handouts template in #11 

Design brief here:
https://docs.google.com/document/d/1EAYGXIcbawbLMWedDhKWH2-zPovxSMTx_YOkNpjDabI/edit#

**Comment by zee-moz** [comment]
@flukeout @cassiemc  we're going to start slide creation for the Berlin workshop this week-- any progress on this issue, or should we move forward with whatever we come up with on our end? 

thanks! z

**Comment by flukeout** [comment]
@zee-moz I'm just getting a last round of feedback on the handout design, and once that's ready I can help with the presentation. If you want to get started and share it with me (you're using Google Slides, yeah?) then I can help once the styles are finalized.

**Comment by zee-moz** [comment]
@flukeout thanks! ideally we'd find a format for slides that's github friendly-- like the handouts, we want to make these materials shareable and remixable (Reveal.js has been mentioned as it supports markdown... I'm not familiar with the range of tools available). 

However, time is really tight... and i don't know that our communities will be _immediately_ remixing our materials... so basically we need something for the presentations now (which is why Google slides came to mind-- are there Mozilla friendly-templates we could start with?). We put our decks on slideshare, and then we'll port materials over into whatever format/platform is best for sharing after the workshop...

Does this make any sense? If you want to hop on a call and discuss, I'm here!

**Comment by zee-moz** [comment]
@cassiemc @flukeout OK, I've asked the team to use the most generic Google slide theme/template, and we'll update per your design friday.

**Comment by flukeout** [comment]
@zee-moz Do you have the presentation started somewhere?

**Comment by zee-moz** [comment]
Hi there, we're working on about 7 short presentations across the team. They are all coming together last-minute! 

I've asked people to use the generic Google Sides template, but there's one presentation that was started early so that was made in Powerpoint using a built in theme... for that one we don't need to adhere to the design elements, and if some of the content feels crowded we can re-format in whatever you design.

Here are the drafts I have now. Different Team members, very different content, so you can see the approaches are all very different...

[GitHub Presentation](https://docs.google.com/a/mozilla.com/presentation/d/17R2EqTq7GM4RyvdG7bNK_g77r50X5-dufzgc5tBmihs/edit?usp=sharing)
[Code of Conduct Presentation, right now entirely big images](https://docs.google.com/a/mozilla.com/presentation/d/1gdWLqP-uHvfp1OZ34VHOz66_XZaJp8JsB8K_3JuKkUs/edit?usp=sharing)
[Data Reuse Presentation](https://docs.google.com/presentation/d/1vOWqL_7MUlEtN4eXQwf36wlmAhYEbhrRNQWp5D9uJws/edit#slide=id.p4)

Will post more as they come!
Z

**Comment by cassiemc** [comment]
@zee-moz Just to clarify what we are delivering – I don't know if we have time to adapt all of these to a new template, so might make sense to just start with one that has built in styles, then your team can port them over. @flukeout what do you think? 

If that's the best way to proceed, @zee-moz which one would you prefer to start with?

**Comment by zee-moz** [comment]
@cassiemc @flukeout I was thinking that you would design a template, and we'd remake each presentation using that template-- we'd put our content into that template. We have a bit of time next week to do that I told everyone to use the google slides generic layouts without any theme (Steph's presentation came before that, so she used ppt, which is where she's most comfortable). 
The GitHub presentation uses that generic google slides template/layouts (more or less-- a bunch of my slides have a heading and a caption, with space for a large image, and I may have made that layout up). Can you start with that? Hope this helps-- I know we didn't talk as much about this issue, so let me know if I misunderstood something. Thanks!

**Comment by cassiemc** [comment]
This is perfect @zee-moz, thanks for confirming, we are definitely on the same page :)

**Comment by flukeout** [comment]
@zee-moz Okay I think I get it - I'll start on making a Google Presentation that accounts for some of the layouts & content in the examples you posted.

**Comment by flukeout** [comment]
**Here we go!**
[Science Labs Presentation Template](https://drive.google.com/open?id=1coTAx-KGWfM8buS5vwiuPjUGoTuWrHJYH1qlcgRIrxY)

**Notes**
- Slides 1-4 are different options for the Cover Slide, let me know your preference
- The rest of the slides can be used within the presentation, you can alternate the background color for emphasis and variety.

**Questions**
- Let me know of any changes you have or anything else I can help with.
  - I can address these over the weekend to get this ready for you for Monday.
- Any other content types that are unaccounted for that you'd need templated?

cc @zee-moz @acabunoc

**Comment by cassiemc** [comment]
Thanks @flukeout! 
@zee-moz Are we good to close this?

**Comment by abbycabs** [comment]
@flukeout - I really like this! Thank you! I can't think of any content types that might be missing. My cover preferences: 4 & 1 (but I like them all!)

the science lab is travelling to Berlin today, so responses will be slow

cc: @cassiemc,

**Comment by cassiemc** [comment]
Thanks @acabunoc! I'm going to close this so that the Plan repo is all cleaned up, but please feel free to file any new follow up issues. Nice work @flukeout! :)

**Comment by stephwright** [comment]
I'm partial to 1 & 3 but think they all look great!  Thanks @flukeout !

**Comment by abbycabs** [comment]
We've decided to use slide 1 for our titles!

cc: @mozillascience/msl-staff
